name: test
on:
  push:
    branches: [ "master" ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: sourcecode CheckOut
      uses: actions/checkout@v3
    - name: build
      run: ./gradlew build

    

